name: simple_stream
description: A simple application that reads integers from a stream and adds their values together.
dependencies:
  args: ^0.10.0

homepage: https://www.dartlang.org/docs/tutorials/streams/
gist: https://gist.github.com/Sfshaza/15d5ef986238c97dbc14
dartpad: https://dartpad.dartlang.org/15d5ef986238c97dbc14
