name: anagram
description: A sample application
dependencies:
  browser: ^0.10.0

homepage: https://www.dartlang.org/docs/tutorials/add-elements/
gist: https://gist.github.com/Sfshaza/0532bfcb70bf5e4a900c
dartpad: https://dartpad.dartlang.org/0532bfcb70bf5e4a900c
