name: search_form
description: A sample application
dependencies:
  browser: ^0.10.0

homepage: https://www.dartlang.org/docs/tutorials/forms/
gist: https://gist.github.com/Sfshaza/67ea796c640ee0328483
dartpad: https://dartpad.dartlang.org/67ea796c640ee0328483
