name: mini_with_style
description: A sample application
dependencies:
  browser: ^0.10.0

homepage: https://www.dartlang.org/docs/tutorials/connect-dart-html/
gist: https://gist.github.com/Sfshaza/ff2ccfff828813c34ffc
dartpad: https://dartpad.dartlang.org/ff2ccfff828813c34ffc
