name: last_positive
description: A simple app that reads from an integer stream and reports the last positive value from the stream.
dependencies:
  args: ^0.10.0

homepage: https://www.dartlang.org/docs/tutorials/streams/
gist: https://gist.github.com/Sfshaza/da80b1e7eed75db53ef3
dartpad: https://dartpad.dartlang.org/da80b1e7eed75db53ef3
