name: todo_with_delete
description: A sample application
dependencies:
  browser: ^0.10.0

homepage: https://www.dartlang.org/docs/tutorials/remove-elements/
gist: https://gist.github.com/Sfshaza/582b9a8d36786566ba08
dartpad: https://dartpad.dartlang.org/582b9a8d36786566ba08
